---
# helm upgrade --install elasticsearch ./ElasticSearch
# This is the internal load balancer, routing traffic to the Elastic Pod
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.infrastructure.appName }}-external"
  namespace: {{ .Values.infrastructure.namespace }}
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - port: 9200
    protocol: TCP
    name: http
  - port: 9300
    protocol: TCP
    name: transport
  selector:
    app: {{ .Values.application.labelValue }}
  selector:
    app: {{ .Values.application.labelValue }}
---
# This is the external load balancer, routing traffic to the Elastic Pod
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.infrastructure.appName }}-internal"
  namespace: {{ .Values.infrastructure.namespace }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - port: 9200
    protocol: TCP
    name: http
  - port: 9300
    protocol: TCP
    name: transport
  selector:
    app: {{ .Values.application.labelValue }}
